services:
  nginx:
    image: nginx:latest
    container_name: attendance_proxy
    ports:
      - "80:80"
    volumes:
      - ../static:/var/www/html/static:ro
      - ./conf.d:/etc/nginx/conf.d/:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      master:
        ipv4_address: 10.0.0.201


networks:
  master:
    external: true